[package]
name = "fstesting"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
quickcheck = "1"
rand = "0.9"
uuid = { version = "1.17", features = ["v7"] }

[build-dependencies]
cc = "1.2"
